# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Gowtham/Desktop/Final Project/VGA_1/VGA_1.srcs/sources_1/ip/image/image.xci
# IP: The module: 'image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gowtham/Desktop/Final Project/VGA_1/VGA_1.srcs/sources_1/ip/image/image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Gowtham/Desktop/Final Project/VGA_1/VGA_1.srcs/sources_1/ip/image/image.xci
# IP: The module: 'image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Gowtham/Desktop/Final Project/VGA_1/VGA_1.srcs/sources_1/ip/image/image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
